services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      # - "443:443"  # For SSL - later
    depends_on:
      - user-service
      - tweet-service
      # Add other services - later
    networks:
      - app-network
      
    # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    container_name: logstash
    volumes:
      - ./logging/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk
    
  notification-service:
    build: ./services/notification-service
    ports:
      - "8004:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - app-network

  follower-service:
    build: ./services/follower-service
    ports:
      - "8005:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network

  search-service:
    build: ./services/search-service
    ports:
      - "8006:8000"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - app-network

  direct-messaging-service:
    build: ./services/direct-messaging-service
    ports:
      - "8007:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - app-network


volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
  app-network:
    driver: bridge

